### ISSUE TITLE
Tests fail to run

### ISSUE THREAD

**Issue by hugihlynsson** [clarkbw/circleci-update-yarn-lock#1]
I just forked and cloned this repo and installed bats 0.4 using homebrew. When running `yarn test` it results in this error:
```Shell
yarn test v0.18.1
$ bats test/*.bats 
bats: ~/Projects/circleci-update-yarn-lock/test/libs/bats-support/load.bash does not exist
error Command failed with exit code 1.
```
I don't have any experience using bats so this might be an obvious mistake on my behalf.

**Comment by clarkbw** [comment]
Oh right, I need to add instructions for the submodules.  Sorry about that.

**Comment by hugihlynsson** [comment]
🙏
